# Example secrets configuration file to be copied to secrets.yaml and modified.
wifi_ssid: "CHANGE_ME"
wifi_password: "CHANGE_ME"

# Password for OTA updates
ota_password: "CHANGE_ME"

# Encryption key for Home Assistant API
api_encryption_key: "CHANGE_ME"
